# Generated by Django 3.1.6 on 2021-03-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=120)),
                ('memory', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=120)),
                ('date', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
